# Site settings
title: Video Cortex
description: 'Insights and Visions'
url: 'http://adishavit.github.io'
baseurl: '/'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Adi Shavit'
  #email: josh@joshgerdes.com
  twitter_username: adishavit
  #facebook_username: joshgerdes
  github_username:  adishavit
  linkedin_username:  adishavit

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
